eLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views
from froala_editor import views as froala_views


admin.site.site_header = "eLMS Administration"
admin.site.site_title = "eLMS Administration Portal"
admin.site.index_title = "Welcome to eLMS Administration Portal"


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('student/', views.guestStudent, name='guestStudent'),
    path('teacher/', views.guestFaculty, name='guestFaculty'),
    path('', include('main.urls')),
    path('', include('discussion.urls')),
    path('', include('attendance.urls')),
    path('', include('quiz.urls')),
    path('froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.myCourses, name='myCourses'),
    path('facultyCourses/', views.facultyCourses, name='facultyCourses'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.course_page, name='course'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('facultyProfile/<str:id>/', views.profile, name='profile_faculty'),
    path('faculty/<int:code>/', views.course_page_faculty, name='faculty'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<int:code>/',
         views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('course-material/<int:code>/',
         views.addCourseMaterial, name='addCourseMaterial'),
    path('course-material/<int:code>/<int:id>/',
         views.deleteCourseMaterial, name='deleteCourseMaterial'),
    path('courses/', views.courses, name='courses'),
    path('departments/', views.departments, name='departments'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordFaculty/', views.changePasswordFaculty,
         name='changePasswordFaculty'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoFaculty/', views.changePhotoFaculty,
         name='changePhotoFaculty'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('student_report/', views.student_report, name = 'student_report')
#     path('student_course/update_status', views.update_student_status, name='update_student_status')
]

main/models.py
from django.db import models
from froala_editor.fields import FroalaField
# Create your models here.


class Student(models.Model):
    student_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    role = models.CharField(
        default="Student", max_length=100, null=False, blank=True)
    course = models.ManyToManyField(
        'Course', related_name='students', blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_student.png')
    department = models.ForeignKey(
        'Department', on_delete=models.CASCADE, null=False, blank=False, related_name='students')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_student.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Students'

    def __str__(self):
        return self.name


class Faculty(models.Model):
    faculty_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    department = models.ForeignKey(
        'Department', on_delete=models.CASCADE, null=False, related_name='faculty')
    role = models.CharField(
        default="Faculty", max_length=100, null=False, blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_faculty.png')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_faculty.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Faculty'

    def __str__(self):
        return self.name


class Department(models.Model):
    department_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Departments'

    def __str__(self):
        return self.name

    def student_count(self):
        return self.students.count()

    def faculty_count(self):
        return self.faculty.count()

    def course_count(self):
        return self.courses.count()


class Course(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=False, related_name='courses')
    faculty = models.ForeignKey(
        Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    studentKey = models.IntegerField(null=False, unique=True)
    facultyKey = models.IntegerField(null=False, unique=True)

    class Meta:
        unique_together = ('code', 'department', 'name')
        verbose_name_plural = "Courses"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    description = FroalaField()

    class Meta:
        verbose_name_plural = "Announcements"
        ordering = ['-datetime']

    def __str__(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")


class Assignment(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    deadline = models.DateTimeField(null=False)
    file = models.FileField(upload_to='assignments/', null=True, blank=True)
    marks = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    class Meta:
        verbose_name_plural = "Assignments"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def due_date(self):
        return self.deadline.strftime("%d-%b-%y, %I:%M %p")


class Submission(models.Model):
    assignment = models.ForeignKey(
        Assignment, on_delete=models.CASCADE, null=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    link = models.CharField(max_length=100, null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    marks = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)

    def file_name(self):
        return self.link

    def time_difference(self):
        difference = self.assignment.deadline - self.datetime
        days = difference.days
        hours = difference.seconds//3600
        minutes = (difference.seconds//60) % 60
        seconds = difference.seconds % 60

        if days == 0:
            if hours == 0:
                if minutes == 0:
                    return str(seconds) + " seconds"
                else:
                    return str(minutes) + " minutes " + str(seconds) + " seconds"
            else:
                return str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"
        else:
            return str(days) + " days " + str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"

    def submission_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    # def delete(self, *args, **kwargs):
    #     self.file.delete()
    #     super().delete(*args, **kwargs)

    def __str__(self):
        return self.student.name + " - " + self.assignment.title

    class Meta:
        unique_together = ('assignment', 'student')
        verbose_name_plural = "Submissions"
        ordering = ['datetime']


class Material(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    file = models.FileField(upload_to='materials/', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Materials"
        ordering = ['-datetime']

    def __str__(self):
        return self.description

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")
    
class StudentCourse(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    is_completed = models.BooleanField(default=False)

class UserSession(models.Model):
    user_id = models.IntegerField()
    user_type = models.CharField(max_length=30)  # 'student' or 'faculty'
    session_key = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(null=True)

main/forms.py
from django import forms
from froala_editor.widgets import FroalaEditor
from .models import Announcement, Assignment, Material


class AnnouncementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnnouncementForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = True
        self.fields['description'].label = ''

    class Meta:
        model = Announcement
        fields = ['description']
        widgets = {
            'description': FroalaEditor(),
        }


class AssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
            field.label = ''
        self.fields['file'].required = False

    class Meta:
        model = Assignment
        fields = ('title', 'description', 'deadline', 'marks', 'file')
        widgets = {
            'description': FroalaEditor(),
            'title': forms.TextInput(attrs={'class': 'form-control mt-1', 'id': 'title', 'name': 'title', 'placeholder': 'Title'}),
            'deadline': forms.DateTimeInput(attrs={'class': 'form-control mt-1', 'id': 'deadline', 'name': 'deadline', 'type': 'datetime-local'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control mt-1', 'id': 'marks', 'name': 'marks', 'placeholder': 'Marks'}),
            'file': forms.FileInput(attrs={'class': 'form-control mt-1', 'id': 'file', 'name': 'file', 'aria-describedby': 'file', 'aria-label': 'Upload'}),
        }


class MaterialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MaterialForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
            field.label = ""
        self.fields['file'].required = False

    class Meta:
        model = Material
        fields = ('description', 'file')
        widgets = {
            'description': FroalaEditor(),
            'file': forms.FileInput(attrs={
                'class': 'form-control', 
                'id': 'file', 
                'name': 'file', 
                'aria-describedby': 'file', 
                'aria-label': 'Upload'
            }),
        }

main/templates/main/Untitled-1.html
<p style="margin-left: 20px">
  <strong>7. Precision Motion: Unleashing Servo Motor Control:</strong>
</p>
<p style="margin-left: 40px">
  Venture into the realm of precise motion control as you tame servo motors with
  PWM sorcery, shaping the physical world with digital finesse.
</p>
<p id="isPasted" style="margin-left: 20px">
  <strong>Procedure (Click on the below link):</strong>
</p>
<p style="margin-left: 20px">
  <strong
    ><a
      class="fr-file"
      href="/media/uploads/froala_editor/files/7.Unleashing%20Servo%20Motor%20Control.pdf"
      rel="noopener noreferrer"
      target="_blank"
      >Unleashing Servo Motor Control</a
    ></strong
  >
</p>
<hr />
<p style="margin-left: 20px">
  <strong>8. Clear the Air: Mastering Air Quality Control:</strong>
</p>
<p style="margin-left: 40px">
  Navigate through the unseen realms of air composition with the ESP32 and MQ2
  sensor, safeguarding environments by detecting and managing harmful gases.
</p>
<p id="isPasted" style="margin-left: 20px">
  <strong>Procedure (Click on the below link):</strong>
</p>
<p style="margin-left: 20px"><strong>-</strong></p>
<hr />
<p style="margin-left: 20px">
  <strong>9. Distance Dictates: Sculpting Smart Distance Monitoring:</strong>
</p>
<p style="margin-left: 40px">
  Embark on a journey of spatial awareness as you employ ultrasonic sensors with
  the ESP32, pioneering applications ranging from obstacle detection to liquid
  level sensing.
</p>
<p style="margin-left: 20px">
  <strong>Procedure (Click on the below link):</strong>
</p>
<p style="margin-left: 20px">
  <a
    class="fr-file"
    href="/media/uploads/froala_editor/files/9.Sculpting%20Smart%20Distance%20Monitoring.pdf"
    rel="noopener noreferrer"
    target="_blank"
    >Sculpting Smart Distance Monitoring</a
  >
</p>

main/templates/main/access.html
{% extends 'index.html' %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' student.student_id %}
{% endblock %}
{% block user %}
{{student.name}}
{% endblock user %}
{% block allCourses %}
{% url 'courses' %}
{% endblock%}
{% block courses %}
{% url 'myCourses' %}
{% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
   <span class="fw-bold"> {{ message }}</span>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}


<div class="container-fluid d-flex" style="min-height: 70vh;">
   <div class="row justify-content-center m-3 align-self-center w-100">
      <div class="col-lg-4 col-sm-12 col-md-6 border p-3 rounded">
         <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
               <label for="key" class="form-label">Enter the access key: </label>
               <input type="number" class="form-control" id="key" name="key" min="0" placeholder="e.g. 1234">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

main/templates/main/all-assignments-std.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Assignments | {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' student.student_id %}
{% endblock %}
{% block user %}
{{student.name}}
{% endblock user %}
{% block courses %}
{% url 'myCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock allCourses %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'myCourses' %}">My
               Courses</a>
            </li>
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
               href="{% url 'course' course.code %}">{{ course.name }}</a></li>
            <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Assignment</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- course name starts -->
      <div class="course-section p-3 m-3 shadow-sm d-flex justify-content-center">
         <div class="fw-bold fs-5 course_name">{{course.department}}-{{course.code}} : {{course.name}}</div>
      </div>
      <!-- course name ends -->
      <!-- assignment section starts -->
      <div class="course-section p-3 m-3 shadow">
         <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/open-book.png' %}"
            alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Assignment</h4>
         <div>
            {% for assignment in assignments %}
            <!-- individual assignment starts -->
            <a class="fw-bold fs-6"
               href="{% url 'assignmentPage' course.code assignment.id %}">{{assignment.title}}</a>
            <div class="fs-6 text-muted border-bottom d-flex justify-content-between">
               <div>
                  {{assignment.post_date}}
               </div>
               <p> Due Date : {{ assignment.due_date}} </p>
            </div>
            <!-- individual assignment ends -->
            {% empty %}
            <h6 style="text-align:center">No assignments given yet</h6>
            {% endfor %}
         </div>
         <div class="text-center fs-6 mt-3">
            <p>Showing {{ assignments.count}} of {{course.assignment_set.count}} {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}</p>
         </div>
      </div>
      <!-- assignment section ends -->
   </div>
</div>
{% endblock %}

main/templates/main/assignment-view.html
{% extends 'index.html' %}
{% load static %}
{% block title %} {{ assignment.title }} - eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block content %}
<!-- navigation links -->
<div class="container shadow-sm">
   <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
      <ol class="breadcrumb p-3">
         <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'facultyCourses' %}">My
            Courses</a>
         </li>
         <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
            href="{% url 'faculty' course.code %}">{{ course.name }}</a></li>
         <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Assignment <span>
            ({{ assignment.title }})</span> 
         </li>
      </ol>
   </nav>
</div>
<!-- navigation links end -->
<div class="container">
   <div class="shadow rounded p-3 assignment-info">
      <p class="px-2 fw-bold fs-5">{{assignment.title}}</p>
      <div class="p-2 text-break">{% autoescape off %}{{assignment.description}}{% endautoescape %}</div>
      <h6 class="p-2 fw-bold">Deadline: <span class="px-2" style="color:red"> {{assignment.due_date}} </span></h6>
      {% if assignment.file %}
      <label class="p-2 fw-bold" for="">Attachment: &nbsp <a
         class="px-2 py-1 text-success bg-success bg-opacity-10 border border-success border-opacity-10 rounded-2"
         style="text-decoration: none; font-size: smaller !important" href="{{assignment.file.url}}"> &nbsp View
      </a> &nbsp or &nbsp <a
         class="fs-6 px-2 py-1 text-primary bg-primary bg-opacity-10 border border-priamry border-opacity-10 rounded-2"
         style="text-decoration: none; font-size: smaller !important" download href=" {{assignment.file.url}}">
      Download</a></label><br>
      {% endif %}
      <label class="p-2 fw-bold" for="">
      Submitted : {{assignment.submission_set.count}}/{{totalStudents}}
      </label><br>
      <label class="p-2 fw-bold" for="">Time Remaining : <span class="fw-semibold" id="timeRemain"></span></label>
   </div>
   <h6 class="text-muted fw-bold fst-italic mt-3">Showing all submissions:</h6>
</div>
<!--Student grading table-->
<div class="container assignment-info">
   <div class="table-responsive">
      <table class="table shadow rounded" style="white-space: nowrap;">
         <thead class="table-dark">
            <tr>
               <th class="text-center" scope="col" colspan="2">Student</th>
               <th class="text-center" scope="col">Student ID</th>
               <th class="text-center" scope="col">Submitted link</th>
               <th class="text-center" scope="col">Submitted on</th>
               <th class="text-center" scope="col" style="min-width: 150px;">Grade</th>
            </tr>
         </thead>
         <tbody>
            {% if not submissions %}
            <td class="text-center text-muted fst-italic" colspan="6">No one has submitted yet</th>
               {% else %}
               {% for submission in submissions %}
            <tr>
               <td class="text-center"><img class="rounded-circle" src="/media/{{ submission.student.photo}}" alt="image"
                  style="height: 2.5rem;"></td>
               <td>{{submission.student.name}}</td>
               <td class="text-center"><span>{{ submission.student_id }}</span></td>
               <td class="text-center"><a
                  class="fw-bold px-2 py-1 text-primary bg-primary bg-opacity-10 border border-priamry border-opacity-10 rounded-2"
                  style="text-decoration: none; font-size: smaller !important" download
                  href="{{submission.link}}" target="_blank">View</a></td>
               <td class="text-center">{{submission.submission_date}}</td>
               {% if submission %}
               <td class="text-center" style="min-width: 150px;">
                  <form action="{% url 'gradeSubmission' course.code assignment.id submission.id %}"
                     method="post">
                     {% csrf_token %}
                     <div class="d-flex justify-content-center">
                        <div class="form-group">
                           <input class="form-control text-center" type="number" placeholder="Marks" name="marks" id="marks"
                              max="{{ assignment.marks}}" step=".1" min="0" value="{{submission.marks}}" required>
                        </div>
                        <button
                           type="submit" class="btn btn-sm ms-2 rounded-2"><img
                           src="{% static 'images/icon/check.png' %}" alt="set" style="height:1rem"></button>
                     </div>
               </td>
               {% else %}
               <td class="text-center" style="min-width: 150px;">
               <form action="{% url 'gradeSubmission' course.code assignment.id submission.id %}"
                  method="post">
               {% csrf_token %}
               <div class="d-flex justify-content-center">
               <div class="form-group">
               <input class="form-control text-center" type="number" placeholder="Marks" name="marks" id="marks"
                  max="{{ assignment.marks}}" step=".1" min="0" required value="{{submission.marks}}"></div><button type="submit"
                  class="btn btn-outline-primary btn-sm ms-2"><img
                  src="{% static 'images/icon/check.png' %}" alt="set" style="height:1rem"></button>
               </div>
               </td>
               {% endif %}
               </form>
            </tr>
            {% endfor %}
            {% endif %}
         </tbody>
      </table>
   </div>
</div>
<script>
   let assignment = document.querySelectorAll('.assignment-info');
   anime({
      targets: assignment,
      opacity: [0, 1],
      easing: 'easeInOutQuad',
      duration: 1500,
      delay: function (el, i) {
         return i * 250;
      }
   });
   
   var time = new Date('{{ assignment.deadline|date:"D, d M Y H:i:s"}}').getTime();
   var rand = setInterval(function () {
       var now = new Date().getTime();
       var difference = time - now;
       var days = Math.floor(difference / (1000 * 60 * 60 * 24));
       var hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
       var minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
       var seconds = Math.floor((difference % (1000 * 60)) / 1000);
   
       document.getElementById("timeRemain").innerHTML = days + " days " + hours + " hours " +
           minutes + " minutes " + seconds + " seconds ";
   
       if (difference < 0) {
           clearInterval(rand);
           document.getElementById("timeRemain").innerHTML = "Closed!";
           document.getElementById("timeRemain").style.color = "red";
       }
   }, 1000);
</script>
{% endblock %}

main/templates/main/facultyCourses.html
{% extends 'index.html' %}
{% block title %}Dashboard | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a class="breadcrumb-item active" aria-current="page">My Courses</a>
            </li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container">
      {% if courses %}
      <!-- course container -->
      <div class="card_primary d-flex justify-content-center flex-wrap">
         {% for courses in courses %}
         <!-- individual course starts -->
         <div class="cd card text-center my-4 mx-4 courseAnim" style="width: 30rem !important;">
            <div class="card-header text-light">
               Dept. of {{courses.department}}
            </div>
            <div class="card-body">
               <h5 class="card-title">{{courses.department}}-{{courses.code}} : {{courses.name}}</h5>
               <a href="{% url 'faculty' courses.code %}" class="btn btn-outline-dark px-5">Enter</a>
            </div>
            <div class="card-footer text-light">
               <svg class="mb-2" xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                  <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                  <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                  <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
               </svg>
               <span class="fs-5">
               {{studentCount|get_item:courses.code}}
               </span>
            </div>
         </div>
         <!-- individual course ends -->
         {% endfor %}
         <!-- course container ends -->
      </div>
      {% else %}
      <div class="text-center h4 text-secondary">No courses to show</div>
      {% endif %}
   </div>
</div>
{% endblock %}